# Generated by Django 2.1.3 on 2019-11-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='版块名称')),
                ('desc', models.CharField(max_length=100, verbose_name='版块描述')),
                ('manager_name', models.CharField(max_length=100, verbose_name='版块管理员名称')),
            ],
        ),
    ]
